### ISSUE TITLE
Planejamento de Reuniões Semanais

### ISSUE THREAD

**Issue by lucasdutraf** [Projeto-Fragelli/Trezentos-App#114]
# Planejamento das reuniões semanais
Issue que mantém a rastreabilidade do que será abordado nos rituais e reuniões.

Torna transparente o que será discutido para definir a próxima sprint.

***

**Comment by lucasdutraf** [comment]
## Planejamento da reunião de 16/12/2018 - _Sprint_ 1

### _Review_ - 30 minutos;  
 - [ ] @GabrielTiveron e @guilherme-mendes  apresentarão as issues #110 e #107 ;   
- [ ] @caiovfernandes  e @VictorLeviPeixoto  apresentarão as issue #102 e #101 ;  
- [ ] @lucasdutraf  e @pedro-prp   apresentarão a issue #82 ;  

### Pré Planejamento _Sprint_ 2           
- Duração: 15 minutos   


##### Issues Planejadas
* **Dívida técnica**
#107 #82 

* **Planejadas**
#117 #104 #103 #108
